baseURL = 'https://blog.headinthecloud.uk'
languageCode = 'en-uk'
title = 'Head In The Cloud'
theme = 'm10c'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[markup]
  [markup.highlight]
    noClasses = false  # Needed to style with CSS
    style = "monokai"  # or any Chroma style